version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: post
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
